---
title: "analyse_descrip"
author: "laurie dussere"
date: '2022-10-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
devtools::install_github("statsbomb/StatsBombR")
'https://statsbomb.com/news/statsbomb-announce-the-release-of-free-statsbomb-360-data-euro-2020-available-now/'
```

```{r warning=FALSE}
library (StatsBombR)
library(ggplot2)
library(ggmosaic)
library(dplyr)
library(tidyverse)
```

```{r}
Comp <- FreeCompetitions()

Matches <- FreeMatches(Comp)

Matches = Matches %>% filter(competition.competition_name=="UEFA Euro")

data360 <- StatsBombFree360Events(MatchesDF = Matches[45,1], Parallel = T)    #[6,1]

events <- StatsBombFreeEvents(MatchesDF = Matches[45,1], Parallel = T)

events <- allclean(events)

events <- get.opposingteam(events)

data360 = data360 %>% rename(id = event_uuid)

events = events %>% left_join(data360, by = c("id" = "id"))

events = events %>% rename(match_id = match_id.x) %>% select(-match_id.y)
```

```{r}
ffs = events %>%
  group_by(team.name) %>%
  filter(type.name=="Pass") %>%
  select(id, match_id, team.name, OpposingTeam, 
         player.name, type.name,
         location.x, location.y, pass.end_location.x,
         pass.end_location.y, pass.recipient.name, freeze_frame,pass.outcome.name,pass.switch,pass.body_part.name,pass.deflected)


ffs = ffs %>% unnest(freeze_frame) %>%
  mutate(ff_location.x = (map(location, 1)), ff_location.y = (map(location, 2))) %>%
  select(-location) %>%
  mutate(ff_location.x = as.numeric(ifelse(ff_location.x == "NULL", NA, ff_location.x)), 
         ff_location.y = as.numeric(ifelse(ff_location.y == "NULL", NA, ff_location.y)))
```

```{r}
#All pass Spain Team
France<-filter(ffs, team.name=="Germany")
#1 pass Spain
France_1<-filter(France, id==c("c5a1e95e-df4d-4c40-b6a0-7d5f785c39c7"))
France_1$teammate[France_1 $teammate == "TRUE"]<-"Germany"
France_1$teammate[France_1 $teammate== "FALSE"]<-"France"
#France_1[,"teammate"]=factor(France_1[,"teammate"],labels=c("Spain","Poland"))
```

```{r}
View(France_1)
```


```{r}
# ## Je vais garder ici que les pass_switch qui sont égales à true 
# # switch : a switch is any pass that travels more than 40 yards of the width od the pitch (40 yards=36m) 
# France_switch=which(France[,"pass.switch"]=="TRUE")
# France_switch=France[France_switch,]
# 
# #ici on va étudier une switch imcomplete
# France_1<-filter(France_switch, id==c("9d1a381e-3ad3-4839-bd17-12a4bfdc5032"))
# France_1$teammate[France_1 $teammate == "TRUE"]<-"Germany"
# France_1$teammate[France_1 $teammate== "FALSE"]<-"France"
# 
# #ici on va étudier une switch qui est pas incomplète
# France_2<-filter(France_switch, id==c("9bfe6af4-32cb-40f5-834f-9a272c576330"))
# France_2$teammate[France_2 $teammate == "TRUE"]<-"Germany"
# France_2$teammate[France_2 $teammate== "FALSE"]<-"France"
# 
# for (i in 1:nrow(France_2)){
#   if (is.na(France_2[i,"pass.outcome.name"])){
#     France_2[i,"pass.outcome.name"]="Not incomplete"
#   }
#   if (is.na(France_2[i,"pass.switch"])){
#     France_2[i,"pass.switch"]="FALSE"
#   }
# }
# 
# pass_player=which(France_1[,"actor"]=="TRUE")
# pass_player=France_1[pass_player,]
```

```{r}

pass_player=which(France_1[,"actor"]=="TRUE")
pass_player=France_1[pass_player,]

ggplot(France_1, aes(x=ff_location.x, y=ff_location.y, label= teammate))+
  geom_point(aes(color=teammate))+
  geom_segment(aes(x=location.x ,y=location.y,xend=pass.end_location.x,yend=pass.end_location.y,color=pass.outcome.name))+
  #geom_segment(aes(x=ff_location.x , y=ff_location.y, xend = 65,  yend = 67))
  # geom_text(size=3, vjust=-2)+
  # geom_blank()+ theme_bw()+
  # #point start
  geom_point(aes(x=location.x , y=location.y),color="purple")+
  geom_point(aes(x=unlist(pass_player[,"ff_location.x"]),y=unlist(pass_player[,"ff_location.y"]),label=teammate),size=4)+
  # #point end
  geom_point(aes(x=pass.end_location.x , y=pass.end_location.y), color="green")+
  guides(color = FALSE, size = FALSE)
  # #point pre-start
  # geom_point(aes(x=43.82309 , y=64.30251, color="Red"))+
  # #move actor
  # geom_segment(aes(x=43.82309 , y=64.30251, xend = 42.7,  yend = 67.9, color="green"))+
  # xlab("Expected Pass Ratio") + ylab("Real Pass Ratio")
```

```{r}
ffs = events %>%
  group_by(team.name) %>%
  filter(type.name=="Pass") %>%
  select(id, match_id, team.name, 
         player.name, position.name, type.name,
         location.x, location.y, pass.end_location.x,under_pressure,pass.height.name,
         pass.end_location.y, pass.recipient.name, freeze_frame,pass.outcome.name,pass.switch,pass.length,pass.cross,pass.aerial_won,pass.body_part.name,pass.deflected)


ffs = ffs %>% unnest(freeze_frame) %>%
  mutate(ff_location.x = (map(location, 1)), ff_location.y = (map(location, 2))) %>%
  select(-location) %>%
  mutate(ff_location.x = as.numeric(ifelse(ff_location.x == "NULL", NA, ff_location.x)), 
         ff_location.y = as.numeric(ifelse(ff_location.y == "NULL", NA, ff_location.y)))


#All pass Spain Team
France<-filter(ffs, team.name=="France")

France_passes=France
#on conserve uniquement la première ligne qui conserne une passe
France_passes <-France_passes %>% slice(1) %>% 
  bind_rows( France_passes %>% filter(id!=lag(id)))
```

```{r warning=FALSE}
#on complète les données manquantes
for (i in 1:nrow(France_passes)){
   if (is.na(France_passes[i,"pass.outcome.name"])){
      France_passes[i,"pass.outcome.name"]="Unknown"
      France_passes[i,"pass.outcome.name"]=factor(France_passes[i,"pass.outcome.name"])
   }
  if (is.na(France_passes[i,"pass.switch"])){
    France_passes[i,"pass.switch"]=FALSE
  }
  if (is.na(France_passes[i,"pass.cross"])){
    France_passes[i,"pass.cross"]=FALSE
  }
  # if (is.na(France_passes[i,"pass.miscommunication"])){
  #   France_passes[i,"pass.miscommunication"]=FALSE
  #}
  if (is.na(France_passes[i,"pass.aerial_won"])){
    France_passes[i,"pass.aerial_won"]=FALSE
  } 
  if (is.na(France_passes[i,"under_pressure"])){
    France_passes[i,"under_pressure"]=FALSE
  } 
  if (is.na(France_passes[i,"pass.deflected"])){
    France_passes[i,"pass.deflected"]=FALSE
  }
}
```

```{r fig.height=15}
ggplot(data = France_passes) +
  geom_mosaic(aes(x=product(pass.outcome.name), fill= pass.switch)) + 
  scale_alpha_manual(values =c(.7,.9)) +
  ylab("True/false")+
  xlab("Variable")+
  ggtitle("Etude des caractéristiques des passes")
```

```{r}
#on supprime les passes où on ne connait pas l'issue 
France_passes2=droplevels(France_passes[-which(France_passes$pass.outcome.name == "Unknown"), ] )
```

```{r fig.height=8}
ggplot(data = France_passes2) +
  geom_mosaic(aes(x=product(pass.outcome.name), fill= pass.switch)) + 
  scale_alpha_manual(values =c(.7,.9)) +
  ylab("True/false")+
  xlab("Variable")+
  ggtitle("Etude des caractéristiques des passes")
```

```{r}
# ggplot(data = France_passes2) +
#   geom_mosaic(aes(x=product(pass.outcome.name), fill= pass.miscommunication)) + 
#   scale_alpha_manual(values =c(.7,.9)) +
#   ylab("True/false")+
#   xlab("Variable")+
#   ggtitle("Etude des caractéristiques des passes")
```

```{r}
ggplot(data = France_passes2) +
  geom_mosaic(aes(x=product(pass.outcome.name), fill= pass.cross)) + 
  scale_alpha_manual(values =c(.7,.9)) +
  ylab("True/false")+
  xlab("Variable")+
  ggtitle("Etude des caractéristiques des passes")
```

```{r}
ggplot(data = France_passes2) +
  geom_mosaic(aes(x=product(pass.outcome.name), fill= under_pressure)) + 
  scale_alpha_manual(values =c(.7,.9)) +
  ylab("True/false")+
  xlab("Variable")+
  ggtitle("Etude des caractéristiques des passes")
```

```{r fig.height=10}
ggplot(data = France_passes2) +
  geom_mosaic(aes(x=product(pass.outcome.name), fill= pass.height.name)) + 
  scale_alpha_manual(values =c(.7,.9)) +
  ylab("True/false")+
  xlab("Variable")+
  ggtitle("Etude des caractéristiques des passes")
```

```{r fig.height=10}
ggplot(data = France_passes2) +
  geom_mosaic(aes(x=product(pass.outcome.name), fill= pass.deflected)) + 
  scale_alpha_manual(values =c(.7,.9)) +
  ylab("True/false")+
  xlab("Variable")+
  ggtitle("Etude des caractéristiques des passes")
```
```{r fig.height=10}
ggplot(data = France_passes2) +
  geom_mosaic(aes(x=product(pass.outcome.name), fill= pass.body_part.name)) + 
  scale_alpha_manual(values =c(.7,.9)) +
  ylab("True/false")+
  xlab("Variable")+
  ggtitle("Etude des caractéristiques des passes")
```


# Etude de la longueur des passes 

```{r}
ggplot(France_passes2) +
  aes(x = under_pressure, y = pass.length) +
  geom_boxplot() +
  geom_jitter(aes(color=pass.outcome.name,shape=pass.switch),alpha=0.8)+
  xlab("under_pressure") +
  ylab("longueur de la passe") +
  ggtitle("etude longueur de la passe")
```
# etude de la position de début de passe

```{r}
ggplot(France_passes2) +
  aes(x = pass.outcome.name, y = location.x) +
  geom_boxplot() +
  geom_jitter(aes(color=pass.height.name,shape=under_pressure),alpha=0.8)+
  xlab("pass outcome") +
  ylab("position début") +
  ggtitle("etude position du début de la passe")
```
```{r}
ggplot(France_passes2, aes(x=location.x, y=pass.length)) + 
  geom_point(aes(color=pass.height.name,shape=pass.outcome.name))+
  geom_smooth(method=lm)

ggplot(France_passes2, aes(x=location.y, y=pass.length)) + 
  geom_point(aes(color=pass.height.name,shape=pass.outcome.name))+
  geom_smooth(method=lm)
```

# moyenne 

```{r}
summary(France_passes2[,"location.x"])
summary(France_passes2[,"location.y"])
summary(France_passes2[,"pass.length"])
```


